kind: pipeline
type: docker
name: default

steps:
- name: validate
  image: php
  pull: if-not-exists
  commands:
  - php -l *.php
  when:
    event:
    - tag

- name: deploy
  image: docker pull jgsqware/svn-client
  pull: if-not-exists
  commands:
  - ./deploy/deploy.sh
  environment:
    SVN_USERNAME:
      from_secret: SVN_USERNAME
    SVN_PASSWORD:
      from_secret: SVN_PASSWORD
    SVN_REPOSITORY: https://plugins.svn.wordpress.org/cleverpush
  when:
    event:
    - tag
